// ===== WEBSITE DATA =====
const categories = [
    { id: 1, name: "AI Tools", icon: "smart_toy", tools: 25, color: "#2563EB" },
    { id: 2, name: "PDF Tools", icon: "description", tools: 20, color: "#7C3AED" },
    { id: 3, name: "Image Tools", icon: "image", tools: 30, color: "#10B981" },
    { id: 4, name: "Video Tools", icon: "videocam", tools: 15, color: "#F59E0B" },
    { id: 5, name: "Audio Tools", icon: "audiotrack", tools: 12, color: "#EC4899" },
    { id: 6, name: "Text Tools", icon: "text_fields", tools: 18, color: "#8B5CF6" },
    { id: 7, name: "Web Tools", icon: "code", tools: 22, color: "#3B82F6" },
    { id: 8, name: "Security Tools", icon: "security", tools: 10, color: "#059669" },
    { id: 9, name: "Calculator Tools", icon: "calculate", tools: 25, color: "#DC2626" },
    { id: 10, name: "Design Tools", icon: "palette", tools: 15, color: "#D97706" },
    { id: 11, name: "Business Tools", icon: "business", tools: 12, color: "#1D4ED8" },
    { id: 12, name: "Social Media Tools", icon: "share", tools: 10, color: "#C026D3" },
    { id: 13, name: "SEO Tools", icon: "trending_up", tools: 8, color: "#0891B2" },
    { id: 14, name: "File Tools", icon: "folder", tools: 15, color: "#059669" },
    { id: 15, name: "Converter Tools", icon: "swap_horiz", tools: 20, color: "#2563EB" },
    { id: 16, name: "Developer Tools", icon: "terminal", tools: 18, color: "#DB2777" },
    { id: 17, name: "Education Tools", icon: "school", tools: 10, color: "#7C3AED" },
    { id: 18, name: "Finance Tools", icon: "payments", tools: 12, color: "#10B981" },
    { id: 19, name: "Health Tools", icon: "favorite", tools: 8, color: "#F59E0B" },
    { id: 20, name: "Productivity Tools", icon: "workspaces", tools: 15, color: "#EC4899" }
];

// Generate 300+ tools
const tools = [];
const toolNames = [
    "AI Image Generator", "PDF to Word Converter", "Video Compressor", "Audio Editor Pro",
    "Text Summarizer", "Code Formatter", "Password Generator", "QR Code Creator",
    "Image Compressor", "PDF Merger", "YouTube Downloader", "MP3 Converter",
    "Grammar Checker", "HTML Validator", "VPN Checker", "Color Picker",
    "Unit Converter", "Invoice Generator", "Social Media Scheduler", "Keyword Finder",
    "File Encryptor", "CSS Minifier", "Resume Builder", "BMI Calculator",
    "Calendar Generator", "Chart Maker", "Email Validator", "IP Lookup",
    "JSON Formatter", "XML Converter", "Markdown Editor", "Base64 Encoder",
    "URL Shortener", "Website Screenshot", "Word Counter", "Plagiarism Checker",
    "Font Generator", "Gradient Maker", "Icon Creator", "Logo Designer",
    "Video Editor", "Audio Recorder", "Screen Recorder", "GIF Maker",
    "PDF Splitter", "Excel to PDF", "PPT Converter", "Image Resizer",
    "Background Remover", "Photo Editor", "Video Trimmer", "Audio Splitter",
    "Text to Speech", "Speech to Text", "Language Translator", "Currency Converter",
    "Time Zone Converter", "Age Calculator", "Date Calculator", "Tip Calculator",
    "Loan Calculator", "Interest Calculator", "Tax Calculator", "Budget Planner",
    "Expense Tracker", "Investment Calculator", "Retirement Planner", "Mortgage Calculator",
    "BMI Calculator", "Calorie Counter", "Workout Planner", "Meal Planner",
    "Sleep Tracker", "Meditation Timer", "Period Tracker", "Pregnancy Calculator",
    "Blood Pressure Tracker", "Sugar Level Tracker", "Allergy Tracker", "Vaccination Tracker",
    "Medicine Reminder", "Doctor Finder", "Hospital Locator", "Ambulance Tracker",
    "First Aid Guide", "Emergency Contacts", "Disaster Alert", "Weather Forecast",
    "Air Quality Index", "Pollution Monitor", "Water Quality", "Soil Testing",
    "Crop Calculator", "Fertilizer Calculator", "Irrigation Planner", "Harvest Calculator",
    "Livestock Tracker", "Animal Health", "Veterinary Help", "Pet Care",
    "Plant Identifier", "Gardening Planner", "Landscape Design", "Interior Design",
    "Architecture Tool", "3D Modeler", "Floor Plan Creator", "Blueprint Maker",
    "Construction Calculator", "Material Estimator", "Project Planner", "Task Manager",
    "Team Collaboration", "Time Tracker", "Attendance System", "Payroll Calculator",
    "Employee Management", "HR Tools", "Recruitment System", "Interview Scheduler",
    "Performance Review", "Training Manager", "Skill Assessment", "Career Planner",
    "Job Search", "Resume Checker", "Cover Letter", "Portfolio Builder",
    "LinkedIn Optimizer", "Networking Tool", "Freelance Manager", "Client Tracker",
    "Invoice Creator", "Contract Generator", "Proposal Maker", "Quote Calculator",
    "Payment Gateway", "Accounting Software", "Bookkeeping", "Tax Filing",
    "Expense Report", "Receipt Scanner", "Mileage Tracker", "Travel Planner",
    "Flight Finder", "Hotel Booking", "Car Rental", "Tour Guide",
    "Map Creator", "Route Planner", "GPS Tracker", "Navigation",
    "Traffic Monitor", "Parking Finder", "Public Transport", "Ride Sharing",
    "Food Delivery", "Restaurant Finder", "Recipe Generator", "Meal Planner",
    "Grocery List", "Nutrition Calculator", "Diet Planner", "Workout Generator",
    "Fitness Tracker", "Step Counter", "Calorie Burn", "Heart Rate Monitor",
    "Sleep Analyzer", "Meditation Guide", "Yoga Instructor", "Mental Health",
    "Stress Relief", "Anxiety Helper", "Depression Aid", "Mood Tracker",
    "Journal App", "Diary Keeper", "Note Taker", "To-Do List",
    "Reminder System", "Alarm Clock", "Timer", "Stopwatch",
    "Calendar Sync", "Event Planner", "Meeting Scheduler", "Conference Call",
    "Video Meeting", "Screen Share", "File Transfer", "Chat Application",
    "Messenger", "Email Client", "News Reader", "RSS Feed",
    "Podcast Player", "Music Player", "Video Player", "Photo Gallery",
    "Cloud Storage", "Backup System", "File Recovery", "Disk Cleaner",
    "PC Optimizer", "Virus Scanner", "Firewall", "Privacy Cleaner",
    "Ad Blocker", "Password Manager", "Two-Factor Auth", "Encryption Tool",
    "VPN Client", "Proxy Server", "Tor Browser", "Dark Web Monitor",
    "Website Blocker", "Parental Control", "Time Limiter", "Focus Mode",
    "Pomodoro Timer", "Distraction Blocker", "Productivity Tracker", "Goal Setter",
    "Habit Tracker", "Reward System", "Motivation Helper", "Learning Assistant",
    "Flashcard Maker", "Quiz Creator", "Test Generator", "Grade Calculator",
    "Homework Helper", "Tutoring System", "Online Course", "Skill Learning",
    "Language Learning", "Coding Practice", "Math Solver", "Science Calculator",
    "Chemistry Lab", "Physics Simulator", "Biology Guide", "History Timeline",
    "Geography Map", "Astronomy Chart", "Art Studio", "Music Composer",
    "Dance Choreographer", "Theater Script", "Film Editor", "Animation Maker",
    "Game Developer", "VR Creator", "AR Tool", "3D Printer",
    "Drone Controller", "Robot Programmer", "IoT Manager", "Smart Home",
    "Energy Monitor", "Water Usage", "Waste Tracker", "Recycling Guide",
    "Carbon Calculator", "Eco Footprint", "Sustainable Living", "Green Energy",
    "Solar Calculator", "Wind Power", "Hydro Energy", "Geothermal",
    "Climate Monitor", "Weather Alert", "Disaster Prepared", "Emergency Kit",
    "First Aid", "Survival Guide", "Navigation Tool", "Compass",
    "Star Map", "Tide Calculator", "Fishing Guide", "Hunting Helper",
    "Camping Planner", "Hiking Tracker", "Climbing Guide", "Cycling Route",
    "Running Tracker", "Swimming Logger", "Sports Analysis", "Team Manager",
    "Tournament Bracket", "Score Keeper", "Stat Tracker", "Player Database",
    "Coach Assistant", "Training Plan", "Injury Prevention", "Recovery Tracker",
    "Nutrition Plan", "Supplement Guide", "Hydration Tracker", "Sleep Monitor",
    "Mental Training", "Visualization Tool", "Breathing Exercise", "Meditation Timer",
    "Yoga Pose", "Stretching Guide", "Massage Timer", "Acupuncture Map",
    "Reflexology Chart", "Aromatherapy", "Herbal Guide", "Home Remedy",
    "Symptom Checker", "Disease Info", "Medicine Guide", "Doctor Chat",
    "Hospital Finder", "Ambulance Call", "First Aid Video", "CPR Guide",
    "Emergency Number", "Safety Alert", "Location Share", "Check-in System",
    "Family Tracker", "Pet Finder", "Item Locator", "Key Finder",
    "Wallet Guard", "Phone Finder", "Laptop Tracker", "Device Manager",
    "Battery Saver", "Data Usage", "Network Speed", "WiFi Analyzer",
    "Signal Booster", "Bluetooth Manager", "Hotspot Creator", "VPN Router",
    "Firewall Setup", "Antivirus Scan", "Malware Removal", "Spyware Detector",
    "Adware Cleaner", "Ransomware Protection", "Phishing Alert", "Fraud Detector",
    "Identity Guard", "Credit Monitor", "Loan Checker", "Debt Calculator",
    "Savings Planner", "Investment Guide", "Retirement Plan", "Pension Calculator",
    "Insurance Quote", "Claim Assistant", "Policy Manager", "Benefit Calculator",
    "Tax Return", "Deduction Finder", "Credit Score", "Report Generator",
    "Document Signer", "Form Filler", "Template Maker", "Format Converter",
    "File Compressor", "Archive Tool", "Extractor", "Burner Software",
    "Disk Imager", "Partition Manager", "Format Tool", "Cleanup Utility",
    "Registry Cleaner", "Driver Updater", "System Info", "Benchmark Tool",
    "Overclocking", "Temperature Monitor", "Fan Control", "Power Saver",
    "Battery Health", "Charging Optimizer", "Data Backup", "Cloud Sync",
    "Version Control", "Code Repository", "Bug Tracker", "Issue Manager",
    "Project Board", "Agile Tool", "Scrum Master", "Kanban Board",
    "Time Estimate", "Resource Planner", "Budget Tracker", "Invoice Generator",
    "Payment Processor", "Receipt Maker", "Expense Report", "Tax Calculator",
    "Legal Document", "Contract Maker", "Agreement Generator", "Signature Collector",
    "Notary Tool", "Witness System", "Evidence Keeper", "Case Manager",
    "Court Date", "Lawyer Finder", "Legal Advice", "Rights Guide",
    "Complaint Letter", "Demand Draft", "Settlement Calculator", "Mediation Tool",
    "Arbitration", "Conflict Resolver", "Peace Maker", "Relationship Helper",
    "Marriage Counselor", "Family Therapy", "Child Care", "Parenting Guide",
    "Baby Tracker", "Pregnancy Week", "Due Date Calculator", "Birth Plan",
    "Baby Names", "Nursery Design", "Feeding Schedule", "Sleep Training",
    "Milestone Tracker", "Vaccination Schedule", "Growth Chart", "Development Check",
    "Education Plan", "School Finder", "College Search", "Scholarship Finder",
    "Admission Helper", "Test Prep", "Practice Test", "Score Calculator",
    "Rank Predictor", "College Predictor", "Career Guide", "Job Matcher",
    "Skill Test", "Aptitude Test", "Personality Test", "Interest Finder",
    "Strength Analyzer", "Weakness Finder", "Opportunity Scanner", "Threat Detector",
    "SWOT Analysis", "Business Plan", "Marketing Strategy", "Sales Forecast",
    "Customer Analysis", "Competitor Research", "Market Research", "Trend Analysis",
    "Data Analyzer", "Report Generator", "Dashboard Maker", "Chart Creator",
    "Graph Plotter", "Map Visualizer", "Timeline Maker", "Infographic Designer",
    "Presentation Tool", "Slide Maker", "Video Presentation", "Pitch Deck",
    "Proposal Maker", "Quote Generator", "Estimate Calculator", "Bid Manager",
    "Auction Tool", "Bidding System", "Reverse Auction", "Dutch Auction",
    "English Auction", "Sealed Bid", "Vickrey Auction", "Combinatorial Auction",
    "Multi-Unit Auction", "Single Unit", "Double Auction", "Call Market",
    "Continuous Trading", "Batch Auction", "Dark Pool", "Light Pool",
    "Exchange System", "Trading Platform", "Order Book", "Matching Engine",
    "Risk Manager", "Margin Calculator", "Leverage Tool", "Hedging Strategy",
    "Arbitrage Finder", "Spread Calculator", "Options Pricing", "Futures Calculator",
    "Swap Valuator", "Derivative Pricing", "Volatility Measure", "Correlation Calculator",
    "Beta Calculator", "Alpha Finder", "Sharpe Ratio", "Sortino Ratio",
    "Treynor Ratio", "Jensen's Alpha", "Information Ratio", "Capture Ratio",
    "Maximum Drawdown", "Value at Risk", "Expected Shortfall", "Stress Test",
    "Scenario Analysis", "Monte Carlo", "Historical Simulation", "Parametric Method",
    "Backtesting Tool", "Forward Testing", "Walk Forward", "Optimization",
    "Genetic Algorithm", "Neural Network", "Machine Learning", "Deep Learning",
    "AI Trainer", "Model Validator", "Data Cleaner", "Feature Engineer",
    "Pattern Finder", "Anomaly Detector", "Outlier Removal", "Cluster Analysis",
    "Classification", "Regression Tool", "Time Series", "Forecasting",
    "Prediction Model", "Recommendation", "Collaborative Filter", "Content Based",
    "Hybrid System", "Ensemble Method", "Boosting", "Bagging",
    "Random Forest", "Decision Tree", "Support Vector", "Neural Network",
    "Deep Learning", "Convolutional NN", "Recurrent NN", "LSTM",
    "GRU", "Transformer", "BERT", "GPT",
    "AI Writer", "AI Painter", "AI Musician", "AI Programmer",
    "AI Designer", "AI Analyst", "AI Consultant", "AI Assistant",
    "Chatbot", "Virtual Agent", "Voice Assistant", "Smart Home",
    "IoT Controller", "Automation", "Scheduler", "Trigger System",
    "Workflow Designer", "Process Map", "Flow Chart", "Mind Map",
    "Organization Chart", "Network Diagram", "UML Designer", "ER Diagram",
    "Database Designer", "SQL Editor", "NoSQL Manager", "Graph Database",
    "Time Series DB", "Document Store", "Key-Value Store", "Column Family",
    "Search Engine", "Index Builder", "Query Optimizer", "Cache Manager",
    "Load Balancer", "Server Monitor", "Application Server", "Web Server",
    "Proxy Server", "DNS Server", "DHCP Server", "Mail Server",
    "File Server", "Print Server", "Backup Server", "Cloud Server",
    "Virtual Machine", "Container", "Docker", "Kubernetes",
    "Orchestration", "Service Mesh", "API Gateway", "Microservices",
    "Monolithic", "Serverless", "Function as Service", "Platform as Service",
    "Infrastructure", "Software as Service", "Desktop as Service", "Database as Service",
    "Backend as Service", "Mobile Backend", "Web Backend", "API Builder",
    "REST API", "GraphQL", "SOAP", "gRPC",
    "WebSocket", "Socket.IO", "MQTT", "AMQP",
    "Kafka", "RabbitMQ", "Redis", "Memcached",
    "MongoDB", "PostgreSQL", "MySQL", "SQLite",
    "Oracle", "SQL Server", "DB2", "Cassandra",
    "CouchDB", "Riak", "Neo4j", "ArangoDB",
    "OrientDB", "JanusGraph", "Dgraph", "TigerGraph",
    "Nebula Graph", "Amazon Neptune", "Azure Cosmos", "Google Cloud Spanner",
    "Firebase", "Supabase", "Appwrite", "Nhost",
    "Hasura", "GraphCMS", "Contentful", "Strapi",
    "Sanity", "Prismic", "Kentico", "Umbraco",
    "WordPress", "Joomla", "Drupal", "Magento",
    "Shopify", "WooCommerce", "BigCommerce", "Squarespace",
    "Wix", "Webflow", "Bubble", "Adalo",
    "Glide", "Thunkable", "Kodular", "MIT App Inventor",
    "Flutter", "React Native", "Ionic", "Xamarin",
    "NativeScript", "Capacitor", "Cordova", "PhoneGap",
    "Swift", "Kotlin", "Java", "Objective-C",
    "C#", "C++", "Python", "JavaScript",
    "TypeScript", "Dart", "Go", "Rust",
    "Ruby", "PHP", "Perl", "Scala",
    "Haskell", "Elixir", "Clojure", "F#",
    "Visual Basic", "Delphi", "Pascal", "Fortran",
    "COBOL", "Lisp", "Prolog", "Ada",
    "Assembly", "Machine Code", "Bytecode", "Intermediate Language",
    "Virtual Machine", "JVM", "CLR", "LLVM",
    "WASM", "WebAssembly", "asm.js", "TypeScript",
    "CoffeeScript", "LiveScript", "PureScript", "ReasonML",
    "ReScript", "Elm", "ClojureScript", "Scala.js",
    "Kotlin/JS", "Dart2JS", "Haxe", "Nim",
    "V", "Zig", "Odin", "Crystal",
    "Julia", "R", "MATLAB", "Octave",
    "Scilab", "Maxima", "Maple", "Mathematica",
    "SageMath", "GAP", "PARI/GP", "Magma",
    "Singular", "Macaulay2", "CoCoA", "4ti2",
    "Normaliz", "Polymake", "TOPCOM", "gfan",
    "PHCpack", "Bertini", "HomotopyContinuation", "NumericalAlgebraicGeometry",
    "SymbolicNumericIntegration", "DifferentialEquations", "PartialDifferentialEquations", "IntegralEquations",
    "FunctionalEquations", "DifferenceEquations", "DelayEquations", "StochasticEquations",
    "RandomProcesses", "ProbabilityDistributions", "StatisticalTests", "HypothesisTesting",
    "ConfidenceIntervals", "RegressionAnalysis", "ANOVA", "MANOVA",
    "FactorAnalysis", "ClusterAnalysis", "DiscriminantAnalysis", "CorrespondenceAnalysis",
    "MultidimensionalScaling", "PrincipalComponentAnalysis", "IndependentComponentAnalysis", "CanonicalCorrelation",
    "TimeSeriesAnalysis", "SpectralAnalysis", "WaveletAnalysis", "FourierAnalysis",
    "SignalProcessing", "ImageProcessing", "VideoProcessing", "AudioProcessing",
    "NaturalLanguageProcessing", "SpeechProcessing", "HandwritingRecognition", "OpticalCharacterRecognition",
    "FaceRecognition", "ObjectDetection", "ImageSegmentation", "InstanceSegmentation",
    "SemanticSegmentation", "PanopticSegmentation", "DepthEstimation", "PoseEstimation",
    "MotionEstimation", "OpticalFlow", "StructureFromMotion", "VisualOdometry",
    "SimultaneousLocalization", "Mapping", "BundleAdjustment", "Photogrammetry",
    "3DReconstruction", "VolumeRendering", "RayTracing", "PathTracing",
    "PhotonMapping", "Radiosity", "AmbientOcclusion", "GlobalIllumination",
    "Caustics", "SubsurfaceScattering", "Translucency", "Transparency",
    "Reflection", "Refraction", "Diffraction", "Interference",
    "Polarization", "Dispersion", "Absorption", "Emission",
    "Scattering", "Attenuation", "Extinction", "Albedo",
    "Irradiance", "Radiance", "Luminance", "Illuminance",
    "LuminousFlux", "LuminousIntensity", "Candela", "Lumen",
    "Lux", "Nit", "Stilb", "Apostilb",
    "Blondel", "Skot", "Bril", "Troland",
    "Phot", "Noct", "Scot", "LuxSecond",
    "Talbot", "LumenSecond", "LumenHour", "CandelaSecond",
    "CandelaHour", "NitSecond", "StilbSecond", "ApostilbSecond",
    "BlondelSecond", "SkotSecond", "BrilSecond", "TrolandSecond",
    "PhotSecond", "NoctSecond", "ScotSecond", "LuxSecondSquare",
    "TalbotSquare", "LumenSecondSquare", "LumenHourSquare", "CandelaSecondSquare",
    "CandelaHourSquare", "NitSecondSquare", "StilbSecondSquare", "ApostilbSecondSquare",
    "BlondelSecondSquare", "SkotSecondSquare", "BrilSecondSquare", "TrolandSecondSquare",
    "PhotSecondSquare", "NoctSecondSquare", "ScotSecondSquare", "LuxSecondCube",
    "TalbotCube", "LumenSecondCube", "LumenHourCube", "CandelaSecondCube",
    "CandelaHourCube", "NitSecondCube", "StilbSecondCube", "ApostilbSecondCube",
    "BlondelSecondCube", "SkotSecondCube", "BrilSecondCube", "TrolandSecondCube",
    "PhotSecondCube", "NoctSecondCube", "ScotSecondCube", "LuxSecondQuartic",
    "TalbotQuartic", "LumenSecondQuartic", "LumenHourQuartic", "CandelaSecondQuartic",
    "CandelaHourQuartic", "NitSecondQuartic", "StilbSecondQuartic", "ApostilbSecondQuartic",
    "BlondelSecondQuartic", "SkotSecondQuartic", "BrilSecondQuartic", "TrolandSecondQuartic",
    "PhotSecondQuartic", "NoctSecondQuartic", "ScotSecondQuartic", "LuxSecondQuintic",
    "TalbotQuintic", "LumenSecondQuintic", "LumenHourQuintic", "CandelaSecondQuintic",
    "CandelaHourQuintic", "NitSecondQuintic", "StilbSecondQuintic", "ApostilbSecondQuintic",
    "BlondelSecondQuintic", "SkotSecondQuintic", "BrilSecondQuintic", "TrolandSecondQuintic",
    "PhotSecondQuintic", "NoctSecondQuintic", "ScotSecondQuintic", "LuxSecondSextic",
    "TalbotSextic", "LumenSecondSextic", "LumenHourSextic", "CandelaSecondSextic",
    "CandelaHourSextic", "NitSecondSextic", "StilbSecondSextic", "ApostilbSecondSextic",
    "BlondelSecondSextic", "SkotSecondSextic", "BrilSecondSextic", "TrolandSecondSextic",
    "PhotSecondSextic", "NoctSecondSextic", "ScotSecondSextic", "LuxSecondSeptic",
    "TalbotSeptic", "LumenSecondSeptic", "LumenHourSeptic", "CandelaSecondSeptic",
    "CandelaHourSeptic", "NitSecondSeptic", "StilbSecondSeptic", "ApostilbSecondSeptic",
    "BlondelSecondSeptic", "SkotSecondSeptic", "BrilSecondSeptic", "TrolandSecondSeptic",
    "PhotSecondSeptic", "NoctSecondSeptic", "ScotSecondSeptic", "LuxSecondOctic"
